name: CI for Lab Work №5 (src)

on:
  push:
    branches:
      - LabWork5
    paths:
      - "Lab Work №5/src/**"
  pull_request:
    branches:
      - LabWork5
    paths:
      - "Lab Work №5/src/**"
  workflow_dispatch:  # Для ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Выгрузка кода из ветки LabWork5
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: LabWork5  # Указываем ветку LabWork5

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Шаг 3: Установка Docker и Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Шаг 4: Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Шаг 5: Установка зависимостей
      - name: Install dependencies
        working-directory: Lab Work №5/src
        run: |
          python -m pip install --upgrade pip
          pip install -r "service1/requirements.txt"
          pip install -r "service2/requirements.txt"
          pip install pytest httpx pytest-asyncio
    
      - name: Build Docker images
        working-directory: Lab Work №5/src
        run: |
          docker-compose build
          docker images

      - name: List Docker images
        run: |
          docker images

      # Шаг 6: Запуск сервисов с помощью Docker Compose
      - name: Start services with Docker Compose
        working-directory: Lab Work №5/src
        run: |
          docker-compose up -d

      # Шаг 7: Ожидание запуска сервисов
      - name: Wait for services to start
        run: |
          sleep 10  # Ждем 10 секунд

      # Шаг 8: Запуск интеграционных тестов
      - name: Run integration tests
        working-directory: Lab Work №5/src
        run: |
          pytest "tests/integration/"

      # Шаг 9: Остановка сервисов (даже если тесты завершились с ошибкой)
      - name: Stop services
        if: always()
        working-directory: Lab Work №5/src
        run: |
          docker-compose down