name: CI for Lab Work №5 (src)

on:
  push:
    branches:
      - LabWork5
    paths:
      - "Lab Work №5/src/**"
  pull_request:
    branches:
      - LabWork5
    paths:
      - "Lab Work №5/src/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory to Lab Work №5/src
        run: cd "Lab Work №5/src"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "service1/requirements.txt"
          pip install -r "service2/requirements.txt"
          pip install pytest httpx pytest-asyncio

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for services to start
        run: |
          sleep 10  # Ждем 10 секунд

      - name: Run integration tests
        run: |
          pytest "tests/integration/"

      - name: Stop services
        if: always()
        run: |
          docker-compose down